#!/bin/bash
# Generate new proprietary-files.txt based on the vendor folder

echo "# This file was automatically generated by proprietary-files_generate.sh" > proprietary-files.txt

find ../../../vendor/asus/X00QD/proprietary -type f | sed "s|../../../vendor/asus/X00QD/proprietary/||" | sort >> proprietary-files.txt

disable_checkelf_libraries=(
  # depends on libmmcamera_interface, which is not yet using Android.bp format
  "libmm-qcamera.so"

  # depends on libsdmutils, which for sdm660 is not yet using Android.bp format, probably we can use other SoC's Android.bp?
  "libsdmextension.so"
  "libsdm-color.so"
  "libsdm-diag.so"
  "libsdm-disp-vndapis.so"

  # depends on libdrmutils, which for sdm660 is not yet using Android.bp format, probably we can use other SoC's Android.bp?
  "libsdedrm.so"
)

for lib in "${disable_checkelf_libraries[@]}"; do
  sed -i "s|${lib}$|${lib};DISABLE_CHECKELF|" proprietary-files.txt
done
